import ExcelJS from 'exceljs';
import fs from 'fs';

async function test() {
    const workbook = new ExcelJS.Workbook();
    // Load the file generated by xlsx-chart
    await workbook.xlsx.readFile('test_chart.xlsx');
    
    console.log('Sheets found:', workbook.worksheets.map(w => w.name));
    
    // Add a new sheet with data
    const sheet = workbook.addWorksheet('Detalle de Equipos');
    sheet.columns = [
        { header: 'ID', key: 'id', width: 10 },
        { header: 'Nombre', key: 'nombre', width: 30 }
    ];
    sheet.addRow({ id: 1, nombre: 'Equipo de Prueba' });
    
    // Save as a new file
    await workbook.xlsx.writeFile('test_preserved.xlsx');
    console.log('File saved as test_preserved.xlsx');
}

test().catch(console.error);
